/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;


import com.mysql.jdbc.Connection;
//import com.sun.istack.internal.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import sun.util.logging.PlatformLogger;
 

/**
 *
 * @author Nipun
 */
public class AdminDetails extends javax.swing.JFrame {
        
    Connection con = null;
    
    PreparedStatement pst = null;
    
    ResultSet rs = null;
    
    ResultSet rs1 = null;
    
    ResultSet rs2 = null;

    /**
     * Creates new form AdminDetails
     */
    public AdminDetails() {
        initComponents();
        
        con = DBconnect.connect();
        
        tableload();
        
    }
    
    public void tableload(){
        
        try{
        
        String q = "SELECT ReservationId, CustomerName FROM resevationdetails";
        
        pst = con.prepareStatement(q);
        
        rs = pst.executeQuery();
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 492));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 50, 375, 158);

        jLabel1.setText("name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 220, 50, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 220, 116, 30);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 280, 80, 25);

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 10, 110, 25);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(381, 280, 90, 25);

        jButton5.setText("generate old customer details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(160, 350, 290, 25);

        jButton4.setText("COD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 400, 57, 25);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 400, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String na;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        
        na = jTextField1.getText();
        
        AdminUP au = new AdminUP();
        
        this.dispose();
        
        au.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        login l = new login();
        
        l.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
                
                int d = JOptionPane.showConfirmDialog(null,"Do you want to refresh the Customer details");
        
        if(d == 0){
            
     
            
            String qa = "SELECT ReservationId, CustomerName, CheckInDate, CheckOutDate FROM resevationdetails WHERE CheckOutDate < CURDATE()"; 
            
            try{
                pst = con.prepareStatement(qa);
                
                rs = pst.executeQuery();
                
                while (rs.next()) {

                   /* int id = Integer.parseInt(rs.getString(1));*/
                     String id = rs.getString(1);
                     String Oname = rs.getString(2);
                     String Indate = rs.getString(3); 
                     String Outdate = rs.getString(4);
                 
            
                   /*  System.out.println(id);
                     System.out.println(Oname);
                     System.out.println(Indate); */

                  /* SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
                   
                    java.util.Date Indate = formatter.parse(rs.getString(3)); 
                                      
                    java.util.Date Outdate = formatter.parse(rs.getString(4)); */

                    try {

                        String qns = "INSERT INTO oldde (ReservationId, CustomerName, CheckInDate, CheckOutDate) values ('"+ id +"', '"+ Oname +"', '"+ Indate +"','"+ Outdate +"')";

                        pst = (PreparedStatement) con.prepareStatement(qns);

                        pst.execute();
                        
                        String fkj = "SELECT RoomId FROM reservedroom WHERE ReservationId = '"+ id +"'";
                        
                        pst = con.prepareStatement(fkj);
                        
                        rs1 = pst.executeQuery();
                        
                        /*System.out.println(rs1);*/
                        
                        while(rs1.next()){
                            
                            String room = rs1.getString(1);
                            
                            try{
                                
                                String vc = "UPDATE hotelrooms SET BookingStatus = 1 WHERE RoomId = '"+ room +"'";
                                
                                pst = con.prepareStatement(vc);
                                
                                pst.execute();
                                
                                
                            }
                            catch(Exception e){
                                
                            }
                            
                        }
                        
                        String gj = "DElETE FROM reservedroom WHERE ReservationId = '"+ id +"'";
                        
                        pst = con.prepareStatement(gj);
                        
                        pst.execute();
                        
                         String hj = "DElETE FROM reservedservice WHERE ReservationId = '"+ id +"'";
                        
                        
                        pst = con.prepareStatement(hj);
                        
                        pst.execute();
                        
                       

                    } catch (Exception e) {

                    }
                
                }    
                
                String xq = "DELETE FROM resevationdetails WHERE CheckOutDate < CURDATE() ";
                
                pst = con.prepareStatement(xq);
                
                pst.execute();
                
                AdminDetails AD1 = new AdminDetails();
        
                 AD1.setVisible(true);
        
                this.dispose();
                
            } 
            
            catch(Exception e){
                
            } 
            
            try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Deluxe' AND Bed = 'Single'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Deluxe' AND Bed = 'Single'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            }
            
             try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Deluxe' AND Bed = 'Double'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Deluxe' AND Bed = 'Double'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            }
            
              try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Standard' AND Bed = 'double'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Standard' AND Bed = 'Double'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            }
              
             try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Suite' AND Bed = 'Single'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Suite' AND Bed = 'Single'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            }
             
            try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Standard' AND Bed = 'Single'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Standard' AND Bed = 'Single'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            } 
             
             try{
                String tos = "SELECT COUNT(RoomId) FROM hotelrooms WHERE BookingStatus = 1 AND RoomName = 'Suite' AND Bed = 'Double'";
                                
                                pst  = con.prepareStatement(tos);
                                
                                rs2 = pst.executeQuery();
                                
                                while(rs2.next()){
                                    
                                    String countno1 = rs2.getString(1);
                                    
                                /*    int countno1 = Integer.parseInt(rs2.getString(1)); */
                                    
                                    System.out.println(countno1);
                                    
                                    try{
                                        String dg1 = "UPDATE roomtype SET AvailableRooms = '"+ countno1 +"' WHERE RoomName = 'Suite' AND Bed = 'Double'";
                                        
                                        pst = con.prepareStatement(dg1);
                                        
                                        pst.execute();
                                    }
                                    
                                    catch(Exception e){
                                        
                                    }
                                    
                                }
            }
            
            catch(Exception e){
                
            } 
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            String report = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\hotel\\oldCusomerDetails.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp,false);
 
            
        }
        catch(Exception e){
            
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String reptext =jTextField2.getText();
        
        String repSQL = "SELECT ReservationId, CustomerName, ContactNo, CheckInDate, CheckOutDate, Email, TotalAmount FROM ResevationDetails WHERE CheckOutDate < '"+ reptext +"' ";
        System.out.println(repSQL);
        try{
            
            JasperDesign jd = JRXmlLoader.load("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\hotel\\whoisout.jrxml");
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(repSQL);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp,false);
            
        }
        catch(JRException e){
            
            Logger.getLogger(Packages.class.getName()).log(Level.SEVERE,null, e);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
