/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Nipun
 */
public class login extends javax.swing.JFrame {
    Connection conn = null;
    
    PreparedStatement pst = null;
    
    ResultSet rs = null;
 
   

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        conn = DBconnect.connect();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(718, 580));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 380, 170, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 420, 110, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 370, 121, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 460, 140, 25);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(320, 410, 121, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(557, 22, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Viajes-y-hoteles-222.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1, -4, 730, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean validate_login(String username, String password){
        
        try{
            
            String fgh = "SELECT * FROM user WHERE username = ? AND password = ?"; 
            
            pst = conn.prepareStatement(fgh);
            
            pst.setString(1, username);
            
            pst.setString(2, password);
            
            rs = pst.executeQuery();
            
            if(rs.next())
                return true;
            else
                return false;
        }
        catch(Exception e){
            e.printStackTrace();
            
            return false;
        }
        
    } 
    
    private boolean is_Manager(){
        
        char[] pass = jPasswordField1.getPassword();
        
        String pvd = String.copyValueOf(pass);  
        
        String chda = "SELECT * FROM user WHERE password = '"+ pvd +"'";
        
        try{
            pst = conn.prepareStatement(chda);
            
            
            
            rs = pst.executeQuery();
            
            while(rs.next()){
                
                String type = rs.getString(3);
            
                /* System.out.println(type);  */
                
                    
            
           if(type.equals("ma")){
               return true;
           }
           
         }
           
          return false; 
            
            
        }
        catch(Exception e){
            
            return false;  
        }
        
        
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String user = jTextField1.getText();
        
        char[] pass = jPasswordField1.getPassword();
        
        String pvd = String.copyValueOf(pass);
        
        
           
            if(validate_login(user,pvd)){
                
                if(is_Manager()){
                
                    this.dispose();
                
                    AdminDetails AD1 = new AdminDetails();
        
                    AD1.setVisible(true);
                }
                else{
                    
                    this.dispose();
                
                    Date1 Da = new Date1();
        
                    Da.setVisible(true);
                }
                         


        
                
                
            }
            else
                JOptionPane.showMessageDialog(null,"Incorrect Login");
            
        
        

        
            jTextField1.setText("");
            
            jPasswordField1.setText("");
                

               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
